-- DROP TABLE TB_PAIS;
-- DROP TABLE TB_ESTADO;
-- DROP TABLE TB_CIDADE;

CREATE TABLE TB_PAIS (
    CO_PAIS INTEGER NOT NULL IDENTITY(1,1),
    NO_PAIS VARCHAR(30) NOT NULL,
    NO_IDIOMA VARCHAR(30),
	CONSTRAINT PK_PAIS PRIMARY KEY (CO_PAIS),
	CONSTRAINT UK_NO_PAIS  UNIQUE (NO_PAIS)
);

CREATE TABLE TB_ESTADO (
	CO_ESTADO VARCHAR(2) NOT NULL,
	NO_ESTADO VARCHAR(30) NOT NULL,
	CO_PAIS INTEGER NOT NULL,
	CONSTRAINT PK_ESTADO PRIMARY KEY (CO_ESTADO),
	CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY (CO_PAIS) REFERENCES TB_PAIS(CO_PAIS),
	CONSTRAINT UK_NO_ESTADO  UNIQUE (NO_ESTADO)
);

CREATE TABLE TB_CIDADE (
	CO_CIDADE INTEGER NOT NULL,
	CO_CEP INTEGER NOT NULL,
	NO_CIDADE VARCHAR(100) NOT NULL,
	CO_ESTADO VARCHAR(2) NOT NULL,
	CONSTRAINT PK_CIDADE PRIMARY KEY (CO_CIDADE),
	CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (CO_ESTADO) REFERENCES TB_ESTADO(CO_ESTADO)
);

INSERT INTO TB_PAIS (
	NO_PAIS,
	NO_IDIOMA
) VALUES (
	'Brasil',
	'Português'
);

INSERT INTO TB_ESTADO (
	CO_ESTADO,
	NO_ESTADO,
	CO_PAIS
) VALUES (
	'SP',
	'São Paulo',
	1
);

INSERT INTO TB_CIDADE (
	CO_CIDADE,
	CO_CEP,
	NO_CIDADE,
	CO_ESTADO
) VALUES (
	3503208,
	14804000,
	'Araraquara',
	'SP'
);

SELECT
	C.CO_CIDADE,
	C.CO_CEP,
	C.NO_CIDADE,
	E.CO_ESTADO,
	E.NO_ESTADO,
	P.CO_PAIS,
	P.NO_PAIS,
	P.NO_IDIOMA
FROM TB_CIDADE C
 LEFT JOIN TB_ESTADO E ON E.CO_ESTADO = C.CO_ESTADO
 LEFT JOIN TB_PAIS P ON P.CO_PAIS = E.CO_PAIS;
