version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - ./docker/mongodb/database:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"