server:
  port: 1337

spring:
  data:
    mongodb:
      database: db_projeto_redis
      host: localhost
      port: 27017
  cache:
    type: redis
    redis:
      time-to-live: 10000
  redis:
    host: localhost
    port: 6379
    password: redis123